# Generated by Django 3.1.2 on 2021-01-01 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=30)),
                ('post_date', models.DateField(auto_now=True)),
                ('post_details', models.CharField(max_length=200)),
                ('post_type', models.CharField(max_length=50)),
                ('uploaded_picture', models.ImageField(upload_to='user/uploaded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.user')),
            ],
        ),
    ]
