# Generated by Django 3.1.2 on 2021-02-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_now=True)),
                ('post_details', models.CharField(max_length=200)),
                ('post_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_picture', models.ImageField(upload_to='user/uploaded')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostManagementSystem.post')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=300)),
                ('dislikes', models.CharField(max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostManagementSystem.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostManagementSystem.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.user')),
            ],
        ),
    ]
