# Generated by Django 3.1.2 on 2021-01-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
