# Generated by Django 3.1.2 on 2021-01-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementSystem', '0001_initial'),
        ('PostManagementSystem', '0002_remove_post_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostManagementSystem.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.user')),
            ],
        ),
    ]
