# Generated by Django 3.1.2 on 2021-02-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('user', models.ManyToManyField(to='UserManagementSystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.CharField(max_length=50)),
                ('messageDate', models.DateTimeField()),
                ('messageText', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagementSystem.user')),
                ('user_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagingsystem.room')),
            ],
        ),
    ]
